# Generated by Django 5.1.2 on 2024-12-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('prioridade', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('posicao', models.CharField(choices=[('left', 'Esquerda'), ('right', 'Direita')], default='right', max_length=10, verbose_name='Posição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-prioridade', 'data_inicio'],
            },
        ),
    ]
