# Generated by Django 5.1.2 on 2024-12-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(help_text='Faça upload da arte do banner com os textos já incluídos', upload_to='banners/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, help_text='Link para onde o banner irá direcionar quando clicado', verbose_name='Link'),
        ),
    ]
