# Generated by Django 5.1.2 on 2024-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='nome_cliente',
            field=models.CharField(blank=True, help_text='Nome do cliente do banner', max_length=200, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
