# Generated by Django 5.1.2 on 2024-12-25 21:58

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_banner_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(help_text='Faça upload da arte do banner no formato 9:16 (540x960 pixels). Use JPEG, PNG ou WEBP.', upload_to='banners/', validators=[banners.models.validate_image_dimensions], verbose_name='Imagem'),
        ),
    ]
