# Generated by Django 5.1.2 on 2025-01-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_alter_banner_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='banners.banner')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BannerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='banners.banner')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
