# Generated by Django 5.1.2 on 2025-01-01 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_bannerclick_bannerview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerclick',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='bannerview',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
    ]
