# Generated by Django 5.1.2 on 2025-01-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_alter_bannerclick_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerclick',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='bannerview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora'),
        ),
        migrations.AddIndex(
            model_name='bannerclick',
            index=models.Index(fields=['-timestamp'], name='banners_ban_timesta_8c6e03_idx'),
        ),
        migrations.AddIndex(
            model_name='bannerview',
            index=models.Index(fields=['-timestamp'], name='banners_ban_timesta_2e3d6b_idx'),
        ),
    ]
