# Generated by Django 5.1.2 on 2024-12-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AramaicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aramaic_word', models.CharField(max_length=200, verbose_name='Palavra Aramaica')),
                ('transliteration', models.CharField(max_length=200, verbose_name='Transliteração')),
                ('portuguese_translation', models.TextField(verbose_name='Tradução em Português')),
                ('pronunciation_audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Áudio da Pronúncia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Palavra Aramaica',
                'verbose_name_plural': 'Palavras Aramaicas',
                'ordering': ['aramaic_word'],
            },
        ),
    ]
