# Generated by Django 5.1.2 on 2024-12-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aramaicword',
            name='pronunciation_audio',
        ),
    ]
