# Generated by Django 5.1.2 on 2024-12-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0003_alter_aramaicword_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria Gramatical',
                'verbose_name_plural': 'Categorias Gramaticais',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Neutro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='notes',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre a gramática', verbose_name='Notas Gramaticais'),
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='number',
            field=models.CharField(blank=True, choices=[('S', 'Singular'), ('P', 'Plural')], max_length=1, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='root_word',
            field=models.CharField(blank=True, help_text='Raiz da palavra em aramaico', max_length=200, verbose_name='Raiz'),
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='grammatical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary_app.grammaticalcategory', verbose_name='Categoria Gramatical'),
        ),
    ]
