# Generated by Django 5.1.2 on 2024-12-23 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '__first__'),
        ('dictionary_app', '0005_favoriteword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Conteúdo da anotação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Se verdadeiro, outros usuários podem ver esta anotação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dictionary_app.aramaicword')),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WordCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.CharField(help_text='Nome do texto de referência', max_length=255)),
                ('reference_location', models.CharField(help_text='Localização no texto (capítulo, linha, etc)', max_length=100)),
                ('context', models.TextField(help_text='Contexto da referência')),
                ('url', models.URLField(blank=True, help_text='Link para o texto de referência, se disponível')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre a referência')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='dictionary_app.aramaicword')),
            ],
            options={
                'verbose_name': 'Referência Cruzada',
                'verbose_name_plural': 'Referências Cruzadas',
                'ordering': ['reference_text', 'reference_location'],
            },
        ),
        migrations.CreateModel(
            name='WordVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Posição da palavra no versículo')),
                ('context', models.TextField(help_text='Trecho do versículo onde a palavra aparece')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_occurrences', to='bible_app.verse')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_occurrences', to='dictionary_app.aramaicword')),
            ],
            options={
                'verbose_name': 'Ocorrência de Palavra',
                'verbose_name_plural': 'Ocorrências de Palavras',
                'ordering': ['verse', 'position'],
                'unique_together': {('word', 'verse', 'position')},
            },
        ),
    ]
