# Generated by Django 5.1.2 on 2024-12-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0006_userannotation_wordcrossreference_wordverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to='dictionary_app.aramaicword', verbose_name='Palavra'),
        ),
    ]
