# Generated by Django 5.1.2 on 2024-12-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0007_alter_favoriteword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannotation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_app.aramaicword'),
        ),
    ]
