# Generated by Django 5.1.2 on 2024-12-23 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '__first__'),
        ('dictionary_app', '0008_alter_userannotation_word'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aramaicword',
            options={'ordering': ['aramaic_word'], 'verbose_name': 'Palavra Aramaica', 'verbose_name_plural': 'Palavras Aramaicas'},
        ),
        migrations.AlterModelOptions(
            name='grammaticalcategory',
            options={'verbose_name': 'Categoria Gramatical', 'verbose_name_plural': 'Categorias Gramaticais'},
        ),
        migrations.AlterModelOptions(
            name='wordcrossreference',
            options={'ordering': ['reference_text'], 'verbose_name': 'Referência', 'verbose_name_plural': 'Referências'},
        ),
        migrations.AlterModelOptions(
            name='wordverse',
            options={'ordering': ['verse'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteword',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wordverse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wordcrossreference',
            name='url',
        ),
        migrations.AddField(
            model_name='wordcrossreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wordverse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='aramaic_word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Neutro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='grammatical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary_app.grammaticalcategory'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='number',
            field=models.CharField(blank=True, choices=[('S', 'Singular'), ('P', 'Plural'), ('D', 'Dual')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='portuguese_translation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='root_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='transliteration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to='dictionary_app.aramaicword'),
        ),
        migrations.AlterField(
            model_name='grammaticalcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grammaticalcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userannotation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='reference_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='reference_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_app.aramaicword'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_app.verse'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_app.aramaicword'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteword',
            unique_together={('word', 'user')},
        ),
        migrations.RemoveField(
            model_name='wordverse',
            name='position',
        ),
    ]
