# Generated by Django 5.1.2 on 2024-12-24 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '__first__'),
        ('dictionary_app', '0010_delete_userannotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aramaicword',
            name='aramaic_word',
            field=models.CharField(max_length=100, verbose_name='Palavra em Aramaico'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Neutro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='grammatical_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary_app.grammaticalcategory', verbose_name='Categoria Gramatical'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='number',
            field=models.CharField(blank=True, choices=[('S', 'Singular'), ('P', 'Plural'), ('D', 'Dual')], max_length=1, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='portuguese_translation',
            field=models.CharField(max_length=200, verbose_name='Tradução em Português'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='root_word',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Palavra Raiz'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='transliteration',
            field=models.CharField(max_length=100, verbose_name='Transliteração'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='favoriteword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to='dictionary_app.aramaicword', verbose_name='Palavra'),
        ),
        migrations.AlterField(
            model_name='grammaticalcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='grammaticalcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='reference_location',
            field=models.CharField(max_length=100, verbose_name='Localização da Referência'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='reference_text',
            field=models.CharField(max_length=200, verbose_name='Texto de Referência'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_app.aramaicword', verbose_name='Palavra'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_app.verse', verbose_name='Versículo'),
        ),
        migrations.AlterField(
            model_name='wordverse',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_app.aramaicword', verbose_name='Palavra'),
        ),
    ]
