# Generated by Django 5.1.2 on 2024-12-25 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0017_remove_wordcrossreference_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordcrossreference',
            options={'ordering': ['word'], 'verbose_name': 'Referência Cruzada', 'verbose_name_plural': 'Referências Cruzadas'},
        ),
        migrations.RemoveField(
            model_name='wordcrossreference',
            name='notes',
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='root_word',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raiz da Palavra'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='wordcrossreference',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='dictionary_app.aramaicword', verbose_name='Palavra'),
        ),
    ]
