# Generated by Django 5.1.2 on 2024-12-25 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0018_alter_wordcrossreference_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aramaicword',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_words', to=settings.AUTH_USER_MODEL, verbose_name='Favoritos'),
        ),
    ]
