# Generated by Django 5.1.2 on 2024-12-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0019_aramaicword_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammaticalcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria Gramatical', 'verbose_name_plural': 'Categorias Gramaticais'},
        ),
        migrations.AlterField(
            model_name='grammaticalcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
