# Generated by Django 5.1.2 on 2025-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0022_remove_aramaicword_verb_person_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aramaicword',
            name='verb_person',
        ),
        migrations.AddField(
            model_name='aramaicword',
            name='verb_person_number',
            field=models.CharField(blank=True, choices=[('1S', '1ª Pessoa Singular'), ('2S', '2ª Pessoa Singular'), ('3S', '3ª Pessoa Singular'), ('1P', '1ª Pessoa Plural'), ('2P', '2ª Pessoa Plural'), ('3P', '3ª Pessoa Plural')], max_length=2, null=True, verbose_name='Pessoa/Número'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='dialect',
            field=models.CharField(blank=True, choices=[('CLASSIC', 'Siríaco Clássico'), ('EASTERN', 'Aramaico Oriental'), ('WESTERN', 'Aramaico Ocidental'), ('IMPERIAL', 'Aramaico Imperial'), ('BIBLICAL', 'Aramaico Bíblico'), ('JEWISH_BAB', 'Aramaico Judaico-Babilônico'), ('JEWISH_PAL', 'Aramaico Judaico-Palestino'), ('SAMARITAN', 'Aramaico Samaritano'), ('MANDAIC', 'Mandéu'), ('PALMYRENE', 'Palmireno'), ('NABATAEAN', 'Nabateu'), ('TUROYO', 'Turoyo'), ('MLAHSO', 'Mlahso'), ('SURETH', 'Sureth/Neo-Aramaico Assírio'), ('CHALDEAN', 'Caldeu/Neo-Aramaico Caldeu'), ('HERTEVIN', 'Hertevin'), ('SENAYA', 'Senaya'), ('LISHANA', 'Lishana Deni'), ('BOHTAN', 'Bohtan'), ('MODERN', 'Siríaco Moderno'), ('OTHER', 'Outro')], max_length=10, null=True, verbose_name='Dialeto'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='verb_tense',
            field=models.CharField(blank=True, choices=[('PERF', 'Perfeito'), ('IMPERF', 'Imperfeito'), ('IMP', 'Imperativo'), ('PART', 'Particípio')], max_length=7, null=True, verbose_name='Tempo Verbal'),
        ),
    ]
