# Generated by Django 5.1.2 on 2025-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0023_remove_aramaicword_verb_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aramaicword',
            name='aramaic_word',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Palavra em Aramaico/Siríaco'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='portuguese_translation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tradução em Português'),
        ),
        migrations.AlterField(
            model_name='aramaicword',
            name='transliteration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transliteração'),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='aramaic_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto em Aramaico/Siríaco'),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='translation',
            field=models.TextField(blank=True, null=True, verbose_name='Tradução'),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='transliteration',
            field=models.TextField(blank=True, null=True, verbose_name='Transliteração'),
        ),
    ]
