# Generated by Django 5.1.6 on 2025-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0025_alter_aramaicword_verb_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aramaicword',
            name='dialect',
            field=models.CharField(blank=True, choices=[('CLASSIC', 'Siríaco Clássico'), ('EASTERN', 'Aramaico Oriental'), ('WESTERN', 'Aramaico Ocidental'), ('IMPERIAL', 'Aramaico Imperial'), ('BIBLICAL', 'Aramaico Bíblico'), ('JEWISH_BAB', 'Aramaico Judaico-Babilônico'), ('JEWISH_PAL', 'Aramaico Judaico-Palestino'), ('SAMARITAN', 'Aramaico Samaritano'), ('MANDAIC', 'Mandéu'), ('PALMYRENE', 'Palmireno'), ('NABATAEAN', 'Nabateu'), ('TUROYO', 'Turoyo'), ('MLAHSO', 'Mlahso'), ('SURETH', 'Sureth/Neo-Aramaico Assírio'), ('CHALDEAN', 'Caldeu/Neo-Aramaico Caldeu'), ('HERTEVIN', 'Hertevin'), ('SENAYA', 'Senaya'), ('LISHANA', 'Lishana Deni'), ('BOHTAN', 'Bohtan'), ('MODERN', 'Siríaco Moderno'), ('GREEK', 'Grego'), ('HEBREW', 'Hebraico'), ('OTHER', 'Outro')], max_length=10, null=True, verbose_name='Dialeto'),
        ),
    ]
