# Generated by Django 5.1.6 on 2025-05-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_app', '0002_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#3498db', help_text='Cor para destacar esta categoria, ex: #3498db', max_length=7, verbose_name='Cor (Hexadecimal)')),
                ('icon', models.CharField(default='bi-bookmark', help_text='Nome do ícone Bootstrap, ex: bi-bookmark', max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria de Conteúdo',
                'verbose_name_plural': 'Categorias de Conteúdo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica se esta é a categoria principal do versículo', verbose_name='É categoria principal')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_app.contentcategory')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_app.verse')),
            ],
            options={
                'verbose_name': 'Categorização de Versículo',
                'verbose_name_plural': 'Categorizações de Versículos',
                'unique_together': {('verse', 'category')},
            },
        ),
    ]
